config/routes.rb
Rentify::Application.routes.draw do

  root :to => 'property_infos#new'

  resources :property_infos
  get 'customers' => 'property_infos#index', as: 'customers'
  get 'property_infos/:id/result' => 'property_infos#result', as: 'result'

end

app/models/property_info.rb
require 'nokogiri'

class PropertyInfo < ActiveRecord::Base

  validates :email, presence: true
  validates :phone_number, presence: true
  validates :postcode, presence: true
  validates :rental_period_type_id, presence: true
  validates :rent_income, presence: true
  validates_numericality_of :rent_income
  validates :property_cost, presence: true
  validates_numericality_of :property_cost

  def rental_yield_calculation
    self.errors.add(:property_cost, 'cannot be zero') if self.property_cost == 0
    return false unless self.errors.empty?

    case self.rental_period_type_id
    when 1
      (self.rent_income.to_f * 12.0 / self.property_cost.to_f).to_d * 100
    when 2
      (self.rent_income.to_f / self.property_cost.to_f).to_d * 100
    end
  end

  def nearby_property_price
  	begin
	  	xml = WebApiUtil.get('api/v1/average_sold_prices.xml', {:postcode => self.postcode, :output_type => 'outcode', :area_type => 'streets', :api_key => 'u5p5yfvmxg3vvw3tubh6s7gn'})
	  	xml = Nokogiri::XML(xml)
	  	return nil if xml.xpath("//average_sold_price_1year").first.nil?
	  	xml.xpath("//average_sold_price_1year").first.content
  	rescue
  		return nil
  	end
  end

  def rent_suggestion
  	case self.rental_period_type_id
    when 1
      my_yield = self.rental_yield_calculation
      suggested_rent = self.nearby_property_price.to_d * (my_yield / 100).to_d / 12.0
    when 2
      my_yield = self.rental_yield_calculation
      suggested_rent = self.nearby_property_price.to_d * (my_yield / 100).to_d * 12.0
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/property_infos_controller.rb
class PropertyInfosController < ApplicationController
  before_action :set_property_info, only: [:show, :edit, :update, :destroy, :result]

  # GET /property_infos
  # GET /property_infos.json
  def index
    @property_infos = PropertyInfo.all
  end

  # GET /property_infos/1
  # GET /property_infos/1.json
  def show
  end

  # GET /property_infos/new
  def new
    @property_info = PropertyInfo.new
  end

  # GET /property_infos/1/edit
  def edit
  end

  # POST /property_infos
  # POST /property_infos.json
  def create
    @property_info = PropertyInfo.new(property_info_params)

    respond_to do |format|
      if @property_info.save
        format.html { redirect_to result_path(@property_info), notice: 'Property info was successfully created.' }
        format.json { render action: 'show', status: :created, location: @property_info }
      else
        format.html { render action: 'new' }
        format.json { render json: @property_info.errors, status: :unprocessable_entity }
      end
    end
  end

  def result
    respond_to do |format|
      if @property_info.rental_yield_calculation
        format.html { @result = @property_info.rental_yield_calculation }
      else
        format.html { render action: 'new' }
        format.json { render json: @property_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /property_infos/1
  # PATCH/PUT /property_infos/1.json
  def update
    respond_to do |format|
      if @property_info.update(property_info_params)
        format.html { redirect_to result_path(@property_info), notice: 'Property info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @property_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /property_infos/1
  # DELETE /property_infos/1.json
  def destroy
    @property_info.destroy
    respond_to do |format|
      format.html { redirect_to property_infos_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_property_info
    @property_info = PropertyInfo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def property_info_params
    params.require(:property_info).permit(:email, :phone_number, :postcode, :rental_period_type_id, :rent_income, :property_cost)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/property_infos_helper.rb
module PropertyInfosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rentify</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/property_infos/_form.html.erb
<%= form_for @property_info, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @property_info && !@property_info.errors.empty? %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&#215;</a>
      <ul>
      <% @property_info.errors.full_messages.each do |msg| %>
        <% if msg.is_a?(String) %>
            <li><%= msg %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :postcode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :postcode, :class => 'text_field' %>
    </div>
  </div>


  <div class="well">
    <div class="control-group">
      <%= f.label :rent_income, :class => 'control-label' %>
      <div class="controls">
        £ <%= f.text_field :rent_income, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :property_cost, :class => 'control-label' %>
      <div class="controls">
        £ <%= f.text_field :property_cost, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :rental_period_type_id, 'Rental Income Period:' %>
      <div class="controls">
        <label class="checkbox inline">
          <%= f.radio_button :rental_period_type_id, 1, :checked => true %>
          Monthly
        </label>
        <label class="checkbox inline">
          <%= f.radio_button :rental_period_type_id, 2 %>
          Annual
        </label>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit 'Calculate', :class => 'btn btn-primary' %>
    </div>
  </div>


<% end %>

app/views/property_infos/edit.html.erb
<div class="page-header">
  <h2>Rental Yield Calculator</h2>
</div>

<%= render :partial => 'form' %>

app/views/property_infos/index.html.erb
<%- model_class = PropertyInfo -%>
<div class="page-header">
  <h2>Customers</h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone_number) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:rental_period_type_id) %></th>
      <th><%= model_class.human_attribute_name(:rent_income) %></th>
      <th><%= model_class.human_attribute_name(:property_cost) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @property_infos.each do |property_info| %>
      <tr>
        <td><%= property_info.id %></td>
        <td><%= property_info.email %></td>
        <td><%= property_info.phone_number %></td>
        <td><%= property_info.postcode %></td>
        <td><%= property_info.rental_period_type_id %></td>
        <td><%= property_info.rent_income %></td>
        <td><%= property_info.property_cost %></td>
        <td><%=l property_info.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_property_info_path(property_info), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      property_info_path(property_info),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_property_info_path,
            :class => 'btn btn-primary' %>

app/views/property_infos/new.html.erb
<div class="page-header">
  <h2>Rental Yield Calculator</h2>
</div>

<div class="hero-unit">
  <h3>Hello!</h3>
   Rental Yield is your annual rental income expressed as a percentage of your property value.<br>
   This calculator can help you to compare yields from different properties in the market.<p />
</div>

<%= render :partial => 'form' %>

app/views/property_infos/result.html.erb
<div class="page-header">
  <h2>Rental Yield Calculator</h2>
</div>

<%= render 'form' %>

<div class="thumbnail">
  <h3>Rental Yield Results</h3>
  <p class="lead"><b>Expected Yield:</b> <%= @result %>%</p>
  <% if @property_info.nearby_property_price %>
	  <p class="lead"><b>Suggested Rent:</b> <%= number_to_currency(@property_info.rent_suggestion) %> per <%= @property_info.rental_period_type_id == 1 ? 'month' : 'year' %></p>
	  <p>Sugguested rent is based on the property average sold price in your area, which is at <strong><%= number_to_currency(@property_info.nearby_property_price.to_i) %></strong>, and your calculated rental yield.</p>
	<% else %>
		<p class="lead"><b>Suggested Rent:</b></p>
		<p class="text-warning">Cannot show rent suggestion due to no property average sold price can be found or incorrect postcode</p>
	<% end %>
</div>

<p>

app/views/property_infos/show.html.erb
<%- model_class = PropertyInfo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @property_info.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_number) %>:</strong></dt>
  <dd><%= @property_info.phone_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @property_info.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rental_period_type_id) %>:</strong></dt>
  <dd><%= @property_info.rental_period_type_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rent_income) %>:</strong></dt>
  <dd><%= @property_info.rent_income %></dd>
  <dt><strong><%= model_class.human_attribute_name(:property_cost) %>:</strong></dt>
  <dd><%= @property_info.property_cost %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              property_info_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_property_info_path(@property_info), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              property_info_path(@property_info),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/property_infos_old/_form.html.erb
<%= form_for(@property_info) do |f| %>
  <% if @property_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property_info.errors.count, "error") %> prohibited this property_info from being saved:</h2>

      <ul>
      <% @property_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="field">
    <%= f.label :rental_period_type_id, 'Rental Income Period:' %><br>
    <%= f.label :rental_period_type_id_1, 'Monthly' %>
    <%= f.radio_button :rental_period_type_id, 1 %>
    <%= f.label :rental_period_type_id_2, 'Annual' %>
    <%= f.radio_button :rental_period_type_id, 2 %>
  </div>
  <div class="field">
    <%= f.label :rent_income %><br>
    £<%= f.text_field :rent_income %>
  </div>
  <div class="field">
    <%= f.label :property_cost %><br>
    £<%= f.text_field :property_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_infos_old/edit.html.erb
<h1>Editing property_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @property_info %> |
<%= link_to 'Back', property_infos_path %>

app/views/property_infos_old/index.html.erb
<h1>Listing property_infos</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Phone number</th>
      <th>Postcode</th>
      <th>Rental period type</th>
      <th>Rent income</th>
      <th>Property cost</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @property_infos.each do |property_info| %>
      <tr>
        <td><%= property_info.email %></td>
        <td><%= property_info.phone_number %></td>
        <td><%= property_info.postcode %></td>
        <td><%= property_info.rental_period_type_id %></td>
        <td><%= property_info.rent_income %></td>
        <td><%= property_info.property_cost %></td>
        <td><%= link_to 'Show', property_info %></td>
        <td><%= link_to 'Edit', edit_property_info_path(property_info) %></td>
        <td><%= link_to 'Destroy', property_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property info', new_property_info_path %>

app/views/property_infos_old/new.html.erb
<h1>New property_info</h1>

<%= render 'form' %>

<%= link_to 'Back', property_infos_path %>

app/views/property_infos_old/result.html.erb
<%= render 'form' %>

<%= @property_info.rental_yield_calculation %>%

app/views/property_infos_old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @property_info.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @property_info.phone_number %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @property_info.postcode %>
</p>

<p>
  <strong>Rental period type:</strong>
  <%= @property_info.rental_period_type_id %>
</p>

<p>
  <strong>Rent income:</strong>
  <%= @property_info.rent_income %>
</p>

<p>
  <strong>Property cost:</strong>
  <%= @property_info.property_cost %>
</p>

<%= link_to 'Edit', edit_property_info_path(@property_info) %> |
<%= link_to 'Back', property_infos_path %>